/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhou_ffmpegdemo_EncodUtil */

#ifndef _Included_com_zhou_ffmpegdemo_EncodUtil
#define _Included_com_zhou_ffmpegdemo_EncodUtil
#ifdef __cplusplus
extern "C" {
#endif
#include <libavformat/avformat.h>
/*
 * Class:     com_zhou_ffmpegdemo_EncodUtil
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_zhou_ffmpegdemo_EncodUtil_init
        (JNIEnv *, jobject);



JNIEXPORT jstring JNICALL
Java_com_zhou_ffmpegdemo_EncodUtil_avcodecInfo(JNIEnv *env, jobject instance);



JNIEXPORT jstring JNICALL
Java_com_zhou_ffmpegdemo_EncodUtil_configInfo(JNIEnv *env, jobject instance);

JNIEXPORT void JNICALL
Java_com_zhou_ffmpegdemo_EncodUtil_decodeMp4(JNIEnv *env, jobject instance, jstring filePath_);

#ifdef __cplusplus
}
#endif
#endif
