/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhou_ffmpegdemo_EncodUtil */

#ifndef _Included_com_zhou_ffmpegdemo_EncodUtil
#define _Included_com_zhou_ffmpegdemo_EncodUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhou_ffmpegdemo_EncodUtil
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhou_ffmpegdemo_EncodUtil_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
